In [1]:
import pandas as pd 
import numpy as np

In [2]:
branches=pd.read_csv(r"C:\Users\Arwa Elewa\Downloads\edited data\branches.csv")
customers=pd.read_csv(r"C:\Users\Arwa Elewa\Downloads\edited data\customers.csv")
menu=pd.read_csv(r"C:\Users\Arwa Elewa\Downloads\edited data\menu.csv")
orders=pd.read_csv(r"C:\Users\Arwa Elewa\Downloads\edited data\orders.csv")

In [3]:
branches

  branch_id    city        manager         country
0      BR01  Berlin  Walter Muller         Germany
1      BR02  Lisbon    Joao  Silva        Portugal
2      BR03  London    Tom Jackson  United Kingdom
3      BR04  Madrid            NaN           Spain
4      BR05   Paris     Remy Monet          France
5      BR01  Berlin  Walter Muller         Germany

In [4]:
branches.isna().sum()

branch_id    0
city         0
manager      1
country      0
dtype: int64

In [5]:

branches = branches.drop_duplicates()

# Replace missing managers with 'Unknown'
branches['manager'] = branches['manager'].fillna('Unknown')
branches.to_csv('cleaned_branches.csv', index=False)

C:\Users\Arwa Elewa\AppData\Local\Temp\ipykernel_28152\1110417063.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  branches['manager'] = branches['manager'].fillna('Unknown')

In [6]:
menu

  item_id           item_name  unit_price
0  ITEM01           beverages        2.95
1  ITEM02             Burgers       12.99
2  ITEM03  Chicken Sandwiches         NaN
3  ITEM04             Fries          3.49
4  ITEM05       Sides & Other       -4.99
5  ITEM02             Burgers       12.99

In [7]:
menu.duplicated().sum()

np.int64(1)

In [8]:
menu.isna().sum()

item_id       0
item_name     0
unit_price    1
dtype: int64

In [9]:
menu = menu.drop_duplicates()

In [10]:
menu['unit_price'] = menu['unit_price'].fillna(5.66)

C:\Users\Arwa Elewa\AppData\Local\Temp\ipykernel_28152\1958320699.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  menu['unit_price'] = menu['unit_price'].fillna(5.66)

In [11]:
menu['unit_price'] = menu['unit_price'].abs()

C:\Users\Arwa Elewa\AppData\Local\Temp\ipykernel_28152\2660471112.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  menu['unit_price'] = menu['unit_price'].abs()

In [12]:
menu

  item_id           item_name  unit_price
0  ITEM01           beverages        2.95
1  ITEM02             Burgers       12.99
2  ITEM03  Chicken Sandwiches        5.66
3  ITEM04             Fries          3.49
4  ITEM05       Sides & Other        4.99

In [13]:
customers

,customer_id,first_name,last_name,age,gender,email,city,registration_date,loyalty_member
0,CUST001,Mia,Davis,40.0,Male,customer1@email.com,Pariis,2021-12-25,Yes
1,CUST002,Ava,Wilson,31.0,Female,customer2@email.com,Lisbon,2021-08-18,No
2,CUST003,Harper,Thomas,61.0,Female,customer3@email.com,Madrid,12-2021,No
3,CUST004,Harper,Jones,33.0,Male,customer4@email.com,Lisbon,2021-03-12,Yes
4,CUST005,Noah,Moore,60.0,Female,customer5@email.com,Lisbon,Jan 2022,No
...,...,...,...,...,...,...,...,...,...
78,CUST079,Jack,Anderson,51.0,Female,customer79@email.com,Paris,2021-11-27,NaN
79,CUST080,William,Johnson,52.0,Female,customer80@email.com,London,2021-09-09,NaN
80,CUST046,Henry,Miller,35.0,Male,customer46@email.com,Berlin,2021-05-04,Yes
81,CUST008,Daniel,Williams,53.0,Female,customer8@email.com,London,2021-09-11,Yes
82,CUST029,Noah,Walker,42.0,Female,customer29@email.com,Berlin,2021-04-21,Yes

In [14]:
customers.tail()

,customer_id,first_name,last_name,age,gender,email,city,registration_date,loyalty_member
78,CUST079,Jack,Anderson,51.0,Female,customer79@email.com,Paris,2021-11-27,NaN
79,CUST080,William,Johnson,52.0,Female,customer80@email.com,London,2021-09-09,NaN
80,CUST046,Henry,Miller,35.0,Male,customer46@email.com,Berlin,2021-05-04,Yes
81,CUST008,Daniel,Williams,53.0,Female,customer8@email.com,London,2021-09-11,Yes
82,CUST029,Noah,Walker,42.0,Female,customer29@email.com,Berlin,2021-04-21,Yes

In [15]:
customers.isna().sum()

customer_id          0
first_name           0
last_name            0
age                  6
gender               4
email                0
city                 4
registration_date    1
loyalty_member       5
dtype: int64

In [16]:
customers["customer_name"] = customers["first_name"] + " " + customers["last_name"]
customers.loc[customers["gender"].isnull(), ["customer_name", "customer_id"]]

       customer_name customer_id
11       James Lewis     CUST012
17    Lucas   Wilson     CUST018
31     Emma Thompson     CUST032
32   Alexander Moore     CUST033

In [17]:
customers.loc[customers["customer_id"] == "CUST012", "gender"] = "Male"
customers.loc[customers["customer_id"] == "CUST018", "gender"] = "Male"
customers.loc[customers["customer_id"] == "CUST032", "gender"] = "Female"
customers.loc[customers["customer_id"] == "CUST033", "gender"] = "Male"

In [18]:
customers.duplicated().sum()

np.int64(2)

In [19]:
customers.drop_duplicates(inplace=True)

In [20]:
customers.duplicated().sum()

np.int64(0)

In [21]:
customers['city'] = customers['city'].fillna('Unknown')

In [22]:
null_cities = customers['city'].isnull()
negative_ages = customers['age'] < 0

print(f"Detected rows with null city: {null_cities.sum()}")
print(f"Detected rows with negative age: {negative_ages.sum()}")

# ---------------------------------------------------------
# 2. Remove the detected rows
# ---------------------------------------------------------
# Keep rows where city is NOT null (using the ~ symbol for 'not')
customers = customers[~null_cities]

# Keep rows where age is NOT negative
customers = customers[~(customers['age'] < 0)]

Detected rows with null city: 0
Detected rows with negative age: 1

In [23]:
null_ages = customers['age'].isnull()

In [24]:
customers=customers[~null_ages]

In [25]:
customers.isna().sum()

customer_id          0
first_name           0
last_name            0
age                  0
gender               0
email                0
city                 0
registration_date    1
loyalty_member       4
customer_name        0
dtype: int64

In [26]:
customers.dtypes

customer_id           object
first_name            object
last_name             object
age                  float64
gender                object
email                 object
city                  object
registration_date     object
loyalty_member        object
customer_name         object
dtype: object

In [27]:
customers['registration_date'] = pd.to_datetime(customers['registration_date'],errors="coerce")

In [28]:
customers["registration_date_original"] = customers["registration_date"]

In [29]:
customers["registration_date_clean"] = pd.to_datetime(
    customers["registration_date_original"],
    errors="coerce",
    format="mixed"
)

In [30]:
wrong_dates = customers[customers["registration_date_clean"].isna()]

wrong_dates[["customer_id", "first_name", "registration_date_original", "registration_date_clean"]]

   customer_id first_name registration_date_original registration_date_clean
2      CUST003     Harper                        NaT                     NaT
4      CUST005       Noah                        NaT                     NaT
14     CUST015       Ella                        NaT                     NaT
64     CUST065    Abigail                        NaT                     NaT

In [31]:
customers["registration_date"] = customers["registration_date_clean"]

customers = customers.drop(columns=[
    "registration_date_original",
    "registration_date_clean"
])

In [32]:
wrong_dates = customers[customers["registration_date"].isna()]

wrong_dates[["customer_id", "first_name", "registration_date"]]

   customer_id first_name registration_date
2      CUST003     Harper               NaT
4      CUST005       Noah               NaT
14     CUST015       Ella               NaT
64     CUST065    Abigail               NaT

In [33]:
customers.sample(10)

,customer_id,first_name,last_name,age,gender,email,city,registration_date,loyalty_member,customer_name
19,CUST020,Ava,Anderson,999.0,Female,customer20@email.com,Berlin,2022-04-22,Yes,Ava Anderson
32,CUST033,Alexander,Moore,30.0,Male,customer33@email.com,Lisbon,2022-08-13,No,Alexander Moore
24,CUST025,Emily,Garcia,35.0,Female,customer25@email.com,Berlin,2022-09-14,Yes,Emily Garcia
21,CUST022,Elizabeth,Davis,60.0,Female,customer22@email.com,London,2022-01-13,Yes,Elizabeth Davis
7,CUST008,Daniel,Williams,53.0,Female,customer8@email.com,London,2021-09-11,Yes,Daniel Williams
37,CUST038,William,Brown,32.0,Female,customer38@email.com,Paris,2021-03-19,No,William Brown
71,CUST072,Alexander,Lewis,54.0,Female,customer72@email.com,berLIN,2022-09-23,Yes,Alexander Lewis
10,CUST011,Benjamin,Walker,65.0,M,customer11@email.com,Madrid,2022-09-29,Yes,Benjamin Walker
70,CUST071,Alexander,Anderson,42.0,Male,customer71@email.com,Lisbon,2021-10-04,No,Alexander Anderson
5,CUST006,Avery,White,24.0,Female,customer6@email.com,Lisbon,2021-02-11,No,Avery White

In [34]:
orders

,order_id,order_date,customer_id,item_id,branch_id,quantity,purchase_type,payment_method,total_sales
0,10452,07-11-2022,CUST015,ITEM04,BR03,573.07,Online,Gift Card,2000.01
1,10453,07-11-2022,CUST004,ITEM01,BR04,745.76,Online,Gift Card,2199.99
2,10454,07-11-2022,CUST036,ITEM05,BR02,200.40,In-store,Gift Card,1000.00
3,10455,08-11-2022,CUST032,ITEM02,BR01,569.67,In-store,Credit Card,7400.01
4,10456,08-11-2022,CUST029,ITEM03,BR01,201.01,In-store,Credit Card,2000.05
...,...,...,...,...,...,...,...,...,...
19995,30447,31-12-2026,CUST055,ITEM03,BR04,248.00,Online,Gift Card,3424.93
19996,30448,31-12-2026,CUST009,ITEM03,BR04,179.09,Drive-thru,Credit Card,2584.09
19997,30449,31-12-2026,CUST017,ITEM03,BR01,80.77,Online,Gift Card,1107.81
19998,30450,31-12-2026,CUST022,ITEM05,BR02,203.77,Online,Credit Card,1364.95
19999,30451,31-12-2026,CUST042,ITEM05,BR03,161.33,Online,Credit Card,987.97

In [35]:
orders.duplicated().sum()

np.int64(0)

In [36]:
orders.isna().sum()

order_id            0
order_date          0
customer_id       745
item_id             0
branch_id           0
quantity            0
purchase_type       0
payment_method      0
total_sales         0
dtype: int64

In [75]:
null_customerid = orders['customer_id'].isnull()

In [76]:
orders=orders[~null_customerid]

In [ ]:
orders.isna().sum()

order_id          0
order_date        0
customer_id       0
item_id           0
branch_id         0
quantity          0
purchase_type     0
payment_method    0
total_sales       0
dtype: int64

In [ ]:
negative_quantity = orders['quantity'] < 0

In [ ]:
negative_quantity.sum()

np.int64(2)

In [ ]:
orders = orders[~(orders['quantity'] < 0)]

In [ ]:
negative_quantity.sum()

np.int64(2)

In [ ]:

print(negative_quantity)

0        False
1        False
2        False
3        False
4        False
         ...
19995    False
19996    False
19997    False
19998    False
19999    False
Name: quantity, Length: 19255, dtype: bool

In [ ]:
negative_rows = orders[orders['quantity'] < 0]
print(negative_rows)

Empty DataFrame
Columns: [order_id, order_date, customer_id, item_id, branch_id, quantity, purchase_type, payment_method, total_sales]
Index: []

In [40]:

# Function to DETECT and return outliers
def detect_outliers_iqr(df, column):
    # Ensure we are only calculating on numbers
    if df[column].dtype in ['int64', 'float64']:
        Q1 = df[column].quantile(0.25)
        Q3 = df[column].quantile(0.75)
        IQR = Q3 - Q1
        
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        
        # The "|" symbol means "OR". We look for values below the lower bound OR above the upper bound
        outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]
        return outliers
        
    return pd.DataFrame() # Return empty if not a numeric column

# ====================================================
# 1. Detect Customer Outliers (Age)
# ====================================================

customers['age'] = pd.to_numeric(customers['age'], errors='coerce')

customer_outliers = detect_outliers_iqr(customers.dropna(subset=['age']), 'age')

print(f"--- Customer Age Outliers: {len(customer_outliers)} found ---")
# Print the first few outliers to see what is wrong with them
if len(customer_outliers) > 0:
    print(customer_outliers[['customer_id', 'first_name', 'age']].head())


# ====================================================
# 2. Detect Order Outliers (Total Sales)
# ====================================================

orders['total_sales'] = pd.to_numeric(orders['total_sales'], errors='coerce')

order_sales_outliers = detect_outliers_iqr(orders.dropna(subset=['total_sales']), 'total_sales')

print(f"\n--- Order Total Sales Outliers: {len(order_sales_outliers)} found ---")
# Print the first few outliers
if len(order_sales_outliers) > 0:
    print(order_sales_outliers[['order_id', 'total_sales']].head())
    
# You can also save your detected outliers to a CSV to review them manually!
# order_sales_outliers.to_csv('sales_outliers_report.csv', index=False)

--- Customer Age Outliers: 2 found ---
   customer_id first_name    age
19     CUST020        Ava  999.0
27     CUST028     Oliver  999.0

--- Order Total Sales Outliers: 3072 found ---
    order_id  total_sales
3      10455      7400.01
7      10459      7199.97
12     10464      7199.97
16     10468      7199.97
21     10473      6800.01

In [43]:
customers_cleaned = customers.drop(customer_outliers.index)
orders_cleaned = orders.drop(order_sales_outliers.index)

In [44]:
# Function to DETECT and return outliers
def detect_outliers_iqr(df, column):
    # Ensure we are only calculating on numbers
    if df[column].dtype in ['int64', 'float64']:
        Q1 = df[column].quantile(0.25)
        Q3 = df[column].quantile(0.75)
        IQR = Q3 - Q1
        
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        
        # The "|" symbol means "OR". We look for values below the lower bound OR above the upper bound
        outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]
        return outliers
        
    return pd.DataFrame() # Return empty if not a numeric column

# ====================================================
# 1. Detect Customer Outliers (Age)
# ====================================================

customers['age'] = pd.to_numeric(customers['age'], errors='coerce')

customer_outliers = detect_outliers_iqr(customers.dropna(subset=['age']), 'age')

print(f"--- Customer Age Outliers: {len(customer_outliers)} found ---")
# Print the first few outliers to see what is wrong with them
if len(customer_outliers) > 0:
    print(customer_outliers[['customer_id', 'first_name', 'age']].head())


# ====================================================
# 2. Detect Order Outliers (Total Sales)
# ====================================================

orders['total_sales'] = pd.to_numeric(orders['total_sales'], errors='coerce')

order_sales_outliers = detect_outliers_iqr(orders.dropna(subset=['total_sales']), 'total_sales')

print(f"\n--- Order Total Sales Outliers: {len(order_sales_outliers)} found ---")
# Print the first few outliers
if len(order_sales_outliers) > 0:
    print(order_sales_outliers[['order_id', 'total_sales']].head())

--- Customer Age Outliers: 2 found ---
   customer_id first_name    age
19     CUST020        Ava  999.0
27     CUST028     Oliver  999.0

--- Order Total Sales Outliers: 3072 found ---
    order_id  total_sales
3      10455      7400.01
7      10459      7199.97
12     10464      7199.97
16     10468      7199.97
21     10473      6800.01

In [45]:
customers['age'] = pd.to_numeric(customers['age'], errors='coerce')

# Turn any age under 0 or over 100 into a blank (NaN)
customers['age'] = np.where((customers['age'] < 0) | (customers['age'] > 100), np.nan, customers['age'])

In [46]:
customers.isna().sum()

customer_id          0
first_name           0
last_name            0
age                  2
gender               0
email                0
city                 0
registration_date    4
loyalty_member       4
customer_name        0
dtype: int64

In [51]:
customers['age']=customers['age'].dropna()

In [52]:
customers

,customer_id,first_name,last_name,age,gender,email,city,registration_date,loyalty_member,customer_name
0,CUST001,Mia,Davis,40.0,Male,customer1@email.com,Pariis,2021-12-25,Yes,Mia Davis
1,CUST002,Ava,Wilson,31.0,Female,customer2@email.com,Lisbon,2021-08-18,No,Ava Wilson
2,CUST003,Harper,Thomas,61.0,Female,customer3@email.com,Madrid,NaT,No,Harper Thomas
3,CUST004,Harper,Jones,33.0,Male,customer4@email.com,Lisbon,2021-03-12,Yes,Harper Jones
4,CUST005,Noah,Moore,60.0,Female,customer5@email.com,Lisbon,NaT,No,Noah Moore
...,...,...,...,...,...,...,...,...,...,...
75,CUST076,Ethan,Jones,63.0,Female,customer76@email.com,London,2022-03-23,No,Ethan Jones
77,CUST078,Emily,Moore,18.0,Male,customer78@email.com,London,2021-10-02,No,Emily Moore
78,CUST079,Jack,Anderson,51.0,Female,customer79@email.com,Paris,2021-11-27,NaN,Jack Anderson
79,CUST080,William,Johnson,52.0,Female,customer80@email.com,London,2021-09-09,NaN,William Johnson
80,CUST046,Henry,Miller,35.0,Male,customer46@email.com,Berlin,2021-05-04,Yes,Henry Miller

In [55]:
customers.isna().sum()

customer_id          0
first_name           0
last_name            0
age                  2
gender               0
email                0
city                 0
registration_date    4
loyalty_member       4
customer_name        0
dtype: int64

In [54]:
customers_cleaned = customers.dropna()

In [56]:
null_ages=customers_cleaned['age'].isnull()

In [58]:
customers = customers_cleaned[~null_ages]

In [59]:
customers

,customer_id,first_name,last_name,age,gender,email,city,registration_date,loyalty_member,customer_name
0,CUST001,Mia,Davis,40.0,Male,customer1@email.com,Pariis,2021-12-25,Yes,Mia Davis
1,CUST002,Ava,Wilson,31.0,Female,customer2@email.com,Lisbon,2021-08-18,No,Ava Wilson
3,CUST004,Harper,Jones,33.0,Male,customer4@email.com,Lisbon,2021-03-12,Yes,Harper Jones
5,CUST006,Avery,White,24.0,Female,customer6@email.com,Lisbon,2021-02-11,No,Avery White
6,CUST007,Benjamin,Taylor,40.0,Male,customer7@email.com,Paris,2021-02-01,No,Benjamin Taylor
...,...,...,...,...,...,...,...,...,...,...
73,CUST074,William,Jones,34.0,Female,customer74@email.com,Berlin,2022-05-11,No,William Jones
74,CUST075,Ella,Jackson,20.0,Male,customer75@email.com,Lisbon,2022-04-22,No,Ella Jackson
75,CUST076,Ethan,Jones,63.0,Female,customer76@email.com,London,2022-03-23,No,Ethan Jones
77,CUST078,Emily,Moore,18.0,Male,customer78@email.com,London,2021-10-02,No,Emily Moore
80,CUST046,Henry,Miller,35.0,Male,customer46@email.com,Berlin,2021-05-04,Yes,Henry Miller

In [60]:
customers.isna().sum()

customer_id          0
first_name           0
last_name            0
age                  0
gender               0
email                0
city                 0
registration_date    0
loyalty_member       0
customer_name        0
dtype: int64

In [61]:
branches

  branch_id    city        manager         country
0      BR01  Berlin  Walter Muller         Germany
1      BR02  Lisbon    Joao  Silva        Portugal
2      BR03  London    Tom Jackson  United Kingdom
3      BR04  Madrid        Unknown           Spain
4      BR05   Paris     Remy Monet          France

In [62]:
customers.sample(10)

,customer_id,first_name,last_name,age,gender,email,city,registration_date,loyalty_member,customer_name
57,CUST058,Isabella,Jones,55.0,Male,customer58@email.com,London,2021-01-13,Yes,Isabella Jones
0,CUST001,Mia,Davis,40.0,Male,customer1@email.com,Pariis,2021-12-25,Yes,Mia Davis
61,CUST062,Alexander,Thompson,56.0,Male,customer62@email.com,Berlin,2022-03-20,Yes,Alexander Thompson
56,CUST057,Avery,Taylor,29.0,Female,customer57@email.com,Paris,2021-12-16,Yes,Avery Taylor
26,CUST027,Harper,Thompson,62.0,Female,customer27@email.com,berLIN,2021-06-17,No,Harper Thompson
42,CUST043,Henry,Walker,39.0,Male,customer43@email.com,Berlin,2021-11-05,No,Henry Walker
37,CUST038,William,Brown,32.0,Female,customer38@email.com,Paris,2021-03-19,No,William Brown
54,CUST055,Luca,Johnson,25.0,Male,customer55@email.com,madrid,2022-06-03,No,Luca Johnson
66,CUST067,Abigail,Williams,45.0,Female,customer67@email.com,Lisbon,2022-03-22,Yes,Abigail Williams
68,CUST069,Ava,Thompson,50.0,Female,customer69@email.com,Unknown,2022-06-19,No,Ava Thompson

In [63]:
customers.dtypes

customer_id                  object
first_name                   object
last_name                    object
age                         float64
gender                       object
email                        object
city                         object
registration_date    datetime64[ns]
loyalty_member               object
customer_name                object
dtype: object

In [64]:
customers['age'] = customers['age'].astype(int)

In [65]:
customers.dtypes

customer_id                  object
first_name                   object
last_name                    object
age                           int64
gender                       object
email                        object
city                         object
registration_date    datetime64[ns]
loyalty_member               object
customer_name                object
dtype: object

In [66]:
branches.dtypes

branch_id    object
city         object
manager      object
country      object
dtype: object

In [68]:
menu.dtypes

item_id        object
item_name      object
unit_price    float64
dtype: object

In [69]:
menu

  item_id           item_name  unit_price
0  ITEM01           beverages        2.95
1  ITEM02             Burgers       12.99
2  ITEM03  Chicken Sandwiches        5.66
3  ITEM04             Fries          3.49
4  ITEM05       Sides & Other        4.99

In [70]:
orders.sample(10)

,order_id,order_date,customer_id,item_id,branch_id,quantity,purchase_type,payment_method,total_sales
13089,23541,12-08-2025,CUST021,ITEM04,BR05,475.25,In-store,Credit Card,2682.39
16558,27010,24-04-2026,CUST063,ITEM04,BR02,566.23,Drive-thru,Credit Card,2971.90
45,10497,16-11-2022,CUST078,ITEM01,BR04,677.97,Drive-thru,Credit Card,2000.01
14706,25158,06-12-2025,CUST055,ITEM05,BR02,250.50,In-store,Credit Card,1455.91
19797,30249,17-12-2026,CUST064,ITM01,BR01,774.59,In-store,Credit Card,3757.29
14003,24455,18-10-2025,CUST005,ITEM05,BR02,130.26,In-store,Gift Card,710.10
16295,26747,04-04-2026,CUST014,ITEM02,BR02,554.35,In-store,Credit Card,9988.86
12882,23334,27-07-2025,CUST005,ITEM01,BR05,605.21,Online,Credit Card,2360.49
4041,14493,07-10-2023,CUST055,ITEM04,BR03,486.50,Online,Gift Card,2115.79
18816,29268,05-10-2026,CUST056,ITEM01,BR03,581.34,Drive-thru,Gift Card,2439.31

In [77]:
orders.isna().sum()

order_id          0
order_date        0
customer_id       0
item_id           0
branch_id         0
quantity          0
purchase_type     0
payment_method    0
total_sales       0
dtype: int64

In [78]:
# Function to DETECT and return outliers
def detect_outliers_iqr(df, column):
    # Ensure we are only calculating on numbers
    if df[column].dtype in ['int64', 'float64']:
        Q1 = df[column].quantile(0.25)
        Q3 = df[column].quantile(0.75)
        IQR = Q3 - Q1
        
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        
        # The "|" symbol means "OR". We look for values below the lower bound OR above the upper bound
        outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]
        return outliers
        
    return pd.DataFrame() # Return empty if not a numeric column

# ====================================================
# 1. Detect Customer Outliers (Age)
# ====================================================

customers['age'] = pd.to_numeric(customers['age'], errors='coerce')

customer_outliers = detect_outliers_iqr(customers.dropna(subset=['age']), 'age')

print(f"--- Customer Age Outliers: {len(customer_outliers)} found ---")
# Print the first few outliers to see what is wrong with them
if len(customer_outliers) > 0:
    print(customer_outliers[['customer_id', 'first_name', 'age']].head())


# ====================================================
# 2. Detect Order Outliers (Total Sales)
# ====================================================

orders['total_sales'] = pd.to_numeric(orders['total_sales'], errors='coerce')

order_sales_outliers = detect_outliers_iqr(orders.dropna(subset=['total_sales']), 'total_sales')

print(f"\n--- Order Total Sales Outliers: {len(order_sales_outliers)} found ---")
# Print the first few outliers
if len(order_sales_outliers) > 0:
    print(order_sales_outliers[['order_id', 'total_sales']].head())

--- Customer Age Outliers: 0 found ---

--- Order Total Sales Outliers: 2944 found ---
    order_id  total_sales
3      10455      7400.01
7      10459      7199.97
12     10464      7199.97
16     10468      7199.97
21     10473      6800.01

C:\Users\Arwa Elewa\AppData\Local\Temp\ipykernel_28152\2853221460.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders['total_sales'] = pd.to_numeric(orders['total_sales'], errors='coerce')

In [79]:
invalid_sales = orders["total_sales"] <= 0

orders = orders[~invalid_sales]

In [80]:
orders

,order_id,order_date,customer_id,item_id,branch_id,quantity,purchase_type,payment_method,total_sales
0,10452,07-11-2022,CUST015,ITEM04,BR03,573.07,Online,Gift Card,2000.01
1,10453,07-11-2022,CUST004,ITEM01,BR04,745.76,Online,Gift Card,2199.99
2,10454,07-11-2022,CUST036,ITEM05,BR02,200.40,In-store,Gift Card,1000.00
3,10455,08-11-2022,CUST032,ITEM02,BR01,569.67,In-store,Credit Card,7400.01
4,10456,08-11-2022,CUST029,ITEM03,BR01,201.01,In-store,Credit Card,2000.05
...,...,...,...,...,...,...,...,...,...
19995,30447,31-12-2026,CUST055,ITEM03,BR04,248.00,Online,Gift Card,3424.93
19996,30448,31-12-2026,CUST009,ITEM03,BR04,179.09,Drive-thru,Credit Card,2584.09
19997,30449,31-12-2026,CUST017,ITEM03,BR01,80.77,Online,Gift Card,1107.81
19998,30450,31-12-2026,CUST022,ITEM05,BR02,203.77,Online,Credit Card,1364.95
19999,30451,31-12-2026,CUST042,ITEM05,BR03,161.33,Online,Credit Card,987.97

In [81]:



customers.to_csv('customers.csv', index=False)
orders.to_csv('orders.csv', index=False)
menu.to_csv('menu.csv', index=False)
branches.to_csv('branches.csv', index=False)

In [83]:
customers.to_csv(r"C:\Users\Arwa Elewa\Downloads\finalprojectNTI\customers.csv", index=False)
orders.to_csv(r"C:\Users\Arwa Elewa\Downloads\finalprojectNTI\orders.csv", index=False)
menu.to_csv(r"C:\Users\Arwa Elewa\Downloads\finalprojectNTI\menu.csv", index=False)
branches.to_csv(r"C:\Users\Arwa Elewa\Downloads\finalprojectNTI\branches.csv", index=False)